# fly.toml file generated for real-estate-app on 2023-04-18T16:02:41+02:00

app = "real-estate-app"
primary_region = "ams"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
